name: Config
on: push
jobs:
        build:
                runs-on: ubuntu-latest
                strategy:
                        matrix:
                                compiler: [gcc]
                steps:
                        - uses: actions/checkout@v2
                        - name: afisare Nume
                          run: echo "Cretan Adrian"
                        - name: Compilare
                          run: gcc -o suma suma.c
                        - name: test1(should be 25)
                          run: ./suma 5 15
                        - name: test2(should be 3)
                          run: ./suma 0 3
                        - name: test3(should exceed lower int bounds)
                          run: ./suma -3 -1
                        - name: test4(should be 10)
                          run: ./suma 3 7
                        - name: test5(should be 0)
                          run: ./suma 0 0
                        - name: test6 
                          run: |
                            if[$(./suma 2 3)=="5";fi
                            if[$(./suma 4 7)=="11";fi  


